### ISSUE TITLE
Password should be hidden

### ISSUE THREAD

**Issue by cathalcurtis** [DaftPoint/StarUML.Teamwork#2]
When changing the preferences for the Teamwork plug in, the password appears in plaintext.
This should be hidden. Also is the password stored securely or in plaintext?

**Comment by DaftPoint** [comment]
Masking the Passwort is fixed in the trunk but actually not released. The Passwort is stored by the StarUML API. Have to check how it is done.

**Comment by cathalcurtis** [comment]
Hi Michael,
Nice to hear from you directly.

To be honest I had other problems with Teamwork plugin and I had to give up
on it regretfully.

I just couldn't seem to get it work for me.
I'd be happy to share my experience with you (so long as its not too time
consuming).
This could be a good learning activity for you/DaftPoint as I tried to use
the plugin without prior knowledge ie I made all the typical mistakes a
regular user would make.

Regards,
Cathal.

On 12 February 2016 at 09:15, Michael Seiler <notifications@github.com>
wrote:

> Masking the Passwort is fixed in the trunk but actually not released. The
> Passwort is stored by the StarUML API. Have to check how it is done.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DaftPoint/StarUML.Teamwork/issues/2#issuecomment-183245137>
> .
>



-- 

email:  cathal.curtis@saretime.com
<cathal.curtis@saretime.com>    tel:  +353872386844
  web:  www.saretime.com

**Comment by DaftPoint** [comment]
Hi Cathal,

that would be great. Its the mistakes that the user made and the bugs he/she found while doing so that I need to make the Plugin better. 
At the moment the Plugin is in a State where there are surrely a bunch of bugs. 
But I wanted to release a "basic-version" on which i can work without to create something alone that the people don't want to use :) 

I hope that with the experience you made I can create a much better Version :)

Regards,
Michael

**Comment by cathalcurtis** [comment]
Perfect, I completely get where you're coming from.
(That's the lean startup way)

Let me know how you would like to proceed.

Regards,
Cathal.

On 12 February 2016 at 10:01, Michael Seiler <notifications@github.com>
wrote:

> Hi Cathal,
>
> that would be great. Its the mistakes that the user made and the bugs
> he/she found while doing so that I need to make the Plugin better.
> At the moment the Plugin is in a State where there are surrely a bunch of
> bugs.
> But I wanted to release a "basic-version" on which i can work without to
> create something alone that the people don't want to use :)
>
> I hope that with the experience you made I can create a much better
> Version :)
>
> Regards,
> Michael
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DaftPoint/StarUML.Teamwork/issues/2#issuecomment-183258314>
> .
>



-- 

email:  cathal.curtis@saretime.com
<cathal.curtis@saretime.com>    tel:  +353872386844
  web:  www.saretime.com

**Comment by M-Seiler** [comment]
Hi Cathal,

first thing I would like to know is what the biggest problems were you had. Did you know how to initialize a project and how to commit to it? Did you know how to oben a project you just created?

I would like to make the workflow more smooth for the user.

Regards,
Michael

**Comment by DaftPoint** [comment]
Hi Cathal,

first thing I would like to know is what the biggest problems were you had. Did you know how to initialize a project and how to commit to it? Did you know how to oben a project you just created?

I would like to make the workflow more smooth for the user.

Regards,
Michael
