### ISSUE TITLE
Teamwork Server Configuration does not filter protocol from `git URL`, or throw error

### ISSUE THREAD

**Issue by sstadelman** [DaftPoint/StarUML.Teamwork#4]
In the Teamwork Server Configuration wizard, the user picks from `HTTP` or `HTTPS` for protocol, but when providing the git URL, it is typical to copy/paste the full URL from github or a project portal, which also includes the protocol.  

If the end user does not account for this, and remove the protocol from their git URL, the communication will fail, due to the faulty URL construction:  `https://<user>:<password>@https://mygithub.com/user/repo`.  

No error is thrown, either when entering the settings, or when attempting to access the repository, using a faulty URL pattern.

**Comment by DaftPoint** [comment]
I should change that. Maybe I will drop the HTTP/HTTPS selection and trust, that the user is pasting the correct URL

**Comment by DaftPoint** [comment]
I changed the preferences and now "http" is added if no protocol (http or https) is set. New Release should be online in few days in the extension-registry
