### ISSUE TITLE
No reaction when create teamwork-project

### ISSUE THREAD

**Issue by ChieLi** [DaftPoint/StarUML.Teamwork#5]
<img width="332" alt="2016-05-11 3 01 18" src="https://cloud.githubusercontent.com/assets/15059296/15172544/46ba8ed8-1789-11e6-8222-28078bc3c711.png">

maybe it is something wrong with my gitURL?

http://code.xxxx.com/xxxx/StarUML.git

pasted from my project on gitlab

**Comment by MrWooJ** [comment]
mine's sticking on this step and I didn't any solution to figure out why!

**Comment by kollarlajos** [comment]
The same here,

**Comment by Graunarmin** [comment]
The Problems still seems to exist - anyone got a solution?
